apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: joy19d41c-java-springboot
  janus-idp.io/tekton: joy19d41c-java-springboot
  backstage.io/kubernetes-id: joy19d41c-java-springboot
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: joy19d41c-java-springboot
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
